#set compiler
CC = g++

#provide debug and turn on warnings
CFLAGS = -g -Wall 

#assign main target
TARGET = main

#assign deletion target for later cleaning
TARGET_DEL = main.exe

#define sources
SRCS = student.cpp address.cpp date.cpp main.cpp

#reassign sources to objects
OBJS = $(SRCS:.cpp=.o)

#NOTFIN
